### ISSUE TITLE
new files are not added to output file

### ISSUE THREAD

**Issue by KiranMantha** [tsuyoshiwada/git-diff-archive#18]
when a new file is added to a repo, GDA is not picking up that file when trying to create output a zip file.

![image](https://user-images.githubusercontent.com/13364465/54814431-bc182000-4cb5-11e9-8363-f4a2660dbcc3.png)

In the above screenshot there are 9 files in changeset out of them 4 are newly added files. But in the console, gda picked only modified files but not newly added files.

**Comment by nerminba** [comment]
KiranMantha it will only pick files that have been commited, if they have not been commited git does not care about them.

**Comment by KiranMantha** [comment]
ok thanks for the info
